USE [master]
GO

/****** Object:  Database [ResVol]    Script Date: 07/05/2015 15:26:57 ******/
CREATE DATABASE [ResVol]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ResVol', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\ResVol.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ResVol_log', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\ResVol_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ResVol] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ResVol].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ResVol] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ResVol] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ResVol] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ResVol] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ResVol] SET ARITHABORT OFF 
GO

ALTER DATABASE [ResVol] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ResVol] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [ResVol] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ResVol] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ResVol] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ResVol] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ResVol] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ResVol] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ResVol] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ResVol] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ResVol] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ResVol] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ResVol] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ResVol] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ResVol] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ResVol] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ResVol] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ResVol] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ResVol] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ResVol] SET  MULTI_USER 
GO

ALTER DATABASE [ResVol] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ResVol] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ResVol] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ResVol] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [ResVol] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ResVol] SET  READ_WRITE 
GO

