USE [master]
GO

/****** Object:  Database [ResHotel]    Script Date: 07/05/2015 15:29:11 ******/
CREATE DATABASE [ResHotel]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ResHotel', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\ResHotel.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ResHotel_log', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\ResHotel_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ResHotel] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ResHotel].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ResHotel] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ResHotel] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ResHotel] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ResHotel] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ResHotel] SET ARITHABORT OFF 
GO

ALTER DATABASE [ResHotel] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ResHotel] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [ResHotel] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ResHotel] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ResHotel] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ResHotel] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ResHotel] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ResHotel] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ResHotel] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ResHotel] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ResHotel] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ResHotel] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ResHotel] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ResHotel] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ResHotel] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ResHotel] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ResHotel] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ResHotel] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ResHotel] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ResHotel] SET  MULTI_USER 
GO

ALTER DATABASE [ResHotel] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ResHotel] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ResHotel] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ResHotel] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [ResHotel] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ResHotel] SET  READ_WRITE 
GO

