//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18449
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Ce code source a été automatiquement généré par Microsoft.VSDesigner, Version 4.0.30319.18449.
// 
#pragma warning disable 1591

namespace RechercheVolsHotels.wsHotel {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceHotelSoap", Namespace="http://tempuri.org/")]
    public partial class ServiceHotel : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback rechercheHotelsOperationCompleted;
        
        private System.Threading.SendOrPostCallback rechercheHotelsAvecDateOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServiceHotel() {
            this.Url = global::RechercheVolsHotels.Properties.Settings.Default.RechercheVolsHotels_wsHotel_ServiceHotel;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event rechercheHotelsCompletedEventHandler rechercheHotelsCompleted;
        
        /// <remarks/>
        public event rechercheHotelsAvecDateCompletedEventHandler rechercheHotelsAvecDateCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/rechercheHotels", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public clsHotel[] rechercheHotels(string ville) {
            object[] results = this.Invoke("rechercheHotels", new object[] {
                        ville});
            return ((clsHotel[])(results[0]));
        }
        
        /// <remarks/>
        public void rechercheHotelsAsync(string ville) {
            this.rechercheHotelsAsync(ville, null);
        }
        
        /// <remarks/>
        public void rechercheHotelsAsync(string ville, object userState) {
            if ((this.rechercheHotelsOperationCompleted == null)) {
                this.rechercheHotelsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrechercheHotelsOperationCompleted);
            }
            this.InvokeAsync("rechercheHotels", new object[] {
                        ville}, this.rechercheHotelsOperationCompleted, userState);
        }
        
        private void OnrechercheHotelsOperationCompleted(object arg) {
            if ((this.rechercheHotelsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.rechercheHotelsCompleted(this, new rechercheHotelsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/rechercheHotelsAvecDate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public clsHotel[] rechercheHotelsAvecDate(string ville, System.DateTime debut, System.DateTime fin) {
            object[] results = this.Invoke("rechercheHotelsAvecDate", new object[] {
                        ville,
                        debut,
                        fin});
            return ((clsHotel[])(results[0]));
        }
        
        /// <remarks/>
        public void rechercheHotelsAvecDateAsync(string ville, System.DateTime debut, System.DateTime fin) {
            this.rechercheHotelsAvecDateAsync(ville, debut, fin, null);
        }
        
        /// <remarks/>
        public void rechercheHotelsAvecDateAsync(string ville, System.DateTime debut, System.DateTime fin, object userState) {
            if ((this.rechercheHotelsAvecDateOperationCompleted == null)) {
                this.rechercheHotelsAvecDateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrechercheHotelsAvecDateOperationCompleted);
            }
            this.InvokeAsync("rechercheHotelsAvecDate", new object[] {
                        ville,
                        debut,
                        fin}, this.rechercheHotelsAvecDateOperationCompleted, userState);
        }
        
        private void OnrechercheHotelsAvecDateOperationCompleted(object arg) {
            if ((this.rechercheHotelsAvecDateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.rechercheHotelsAvecDateCompleted(this, new rechercheHotelsAvecDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clsHotel {
        
        private int idField;
        
        private string nomField;
        
        private string villeField;
        
        private System.DateTime debutDispoField;
        
        private System.DateTime finDispoField;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string nom {
            get {
                return this.nomField;
            }
            set {
                this.nomField = value;
            }
        }
        
        /// <remarks/>
        public string ville {
            get {
                return this.villeField;
            }
            set {
                this.villeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime debutDispo {
            get {
                return this.debutDispoField;
            }
            set {
                this.debutDispoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime finDispo {
            get {
                return this.finDispoField;
            }
            set {
                this.finDispoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void rechercheHotelsCompletedEventHandler(object sender, rechercheHotelsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class rechercheHotelsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal rechercheHotelsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public clsHotel[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((clsHotel[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void rechercheHotelsAvecDateCompletedEventHandler(object sender, rechercheHotelsAvecDateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class rechercheHotelsAvecDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal rechercheHotelsAvecDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public clsHotel[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((clsHotel[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591